  - name: added Facts Ubuntu
    set_fact:
      my_vhosts: denisdebian.devops.rebrain.srwx.net
    when: ansible_os_family == "Debian"

  - name: added Facts RedHat
    set_fact:    
      my_vhosts: denisredhat.devops.rebrain.srwx.net
    when: ansible_os_family == "RedHat"  

  - name: add folder for item and sertifications virtual hosts
    file:
      path: /opt/myprojects/{{ item }}
      state: directory
      mode: '0755'
    with_items: 
      - "{{ dir_names }}"
    tags:
      - add_opt_folders

  - name: copy the nginx vhosts config file and the content of the web site on centos
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}" 
    with_items:
      - "{{ virtualconf }}"    
    tags:
      - erste_templates
    notify: 
      - reload nginx 

  - name: make and copy folders and item, Check NGINX
    include_tasks: "{{ ansible_os_family }}.yml"

  - name: Flush handlers
    meta: flush_handlers    
